import type { Match, Innings } from '@/types/match.types';
import type { InningsStats } from '@/types/delivery.types';
import { formatDate, formatScore, formatOversShort } from './format';
import { bowlerOversDisplay } from './cricket';

export function buildShareText(
  match: Match,
  innings1: Innings,
  inn1Stats: InningsStats,
  innings2: Innings | null,
  inn2Stats: InningsStats | null
): string {
  const team = (id: string) => match.teams.find((t) => t.id === id);
  const player = (id: string, teamId?: string) => {
    const t = teamId ? team(teamId) : match.teams[0];
    return t?.players.find((p) => p.id === id)?.name ?? id;
  };

  const lines: string[] = [];
  lines.push(`🏏 ${match.teams[0].name} vs ${match.teams[1].name}`);
  lines.push(`Date: ${formatDate(match.createdAt)}`);
  lines.push('');

  const writeInnings = (innings: Innings, stats: InningsStats, label: string) => {
    const battingTeam = team(innings.battingTeamId);
    lines.push(`${label}: ${battingTeam?.name ?? '?'} — ${formatScore(stats.totalRuns, stats.wickets)} (${formatOversShort(stats.legalBalls)} ov)`);

    // Top batsmen
    const batsmen = Object.values(stats.batsmanScores)
      .filter((b) => b.balls > 0 || b.runs > 0)
      .sort((a, b) => b.runs - a.runs)
      .slice(0, 3);
    for (const b of batsmen) {
      lines.push(`  ${player(b.playerId, innings.battingTeamId)}: ${b.runs} (${b.balls})`);
    }

    // Top bowlers
    const bowlers = Object.values(stats.bowlerScores)
      .filter((b) => b.legalBalls > 0)
      .sort((a, b) => b.wickets - a.wickets || a.runs - b.runs)
      .slice(0, 3);
    for (const b of bowlers) {
      lines.push(`  ${player(b.playerId, innings.bowlingTeamId)}: ${bowlerOversDisplay(b.legalBalls)}-${b.maidens}-${b.runs}-${b.wickets}`);
    }
    lines.push('');
  };

  writeInnings(innings1, inn1Stats, '1st Innings');
  if (innings2 && inn2Stats) writeInnings(innings2, inn2Stats, '2nd Innings');

  if (match.result) {
    lines.push(`Result: ${match.result.resultText}`);
  }
  lines.push('');
  lines.push('Generated by CricScore');

  return lines.join('\n');
}

export async function shareScorecard(text: string): Promise<'shared' | 'copied' | 'failed'> {
  if (navigator.share) {
    try {
      await navigator.share({ title: 'Cricket Scorecard', text });
      return 'shared';
    } catch {
      // user cancelled or share failed
    }
  }
  if (navigator.clipboard) {
    try {
      await navigator.clipboard.writeText(text);
      return 'copied';
    } catch {
      // clipboard denied
    }
  }
  return 'failed';
}
